import React from 'react'
const HomePage = () => {
  return (
    <div className='homePage'>
      <h1 className='brandName'>Chaussure</h1>
      <div>
      <h2>About Us</h2>
      <h2 className='ourMission'>Our Mission: Sell You Shoes!</h2>
      <p><img className='firstP' src='https://image.peltzshoes.com/images/products/1_2245632_ZM.jpg' /> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Etiam tempor orci eu lobortis elementum nibh. Magna ac placerat vestibulum lectus. Sociis natoque penatibus et magnis dis parturient. Mauris cursus mattis molestie a iaculis at erat pellentesque. Tristique senectus et netus et. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Enim diam vulputate ut pharetra sit amet aliquam id diam. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Egestas sed sed risus pretium. Mauris commodo quis imperdiet massa. Non pulvinar neque laoreet suspendisse. Vel pharetra vel turpis nunc eget. Egestas sed tempus urna et pharetra pharetra massa massa. Aliquet enim tortor at auctor. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Integer vitae justo eget magna. Etiam tempor orci eu lobortis.</p>
      </div>
      <div className='secondDiv'>
      <h2 className='buyShoes'>Buy our Shoes</h2>
      <p><img className='secondP' src='https://static01.nyt.com/images/2020/10/29/fashion/26SNEAKERSPILL-wall/merlin_178616268_63bd34d3-8c9d-4d20-9ac2-0e16e20eadca-articleLarge.jpg?quality=75&auto=webp&disable=upscale' /> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Etiam tempor orci eu lobortis elementum nibh. Magna ac placerat vestibulum lectus. Sociis natoque penatibus et magnis dis parturient. Nullam eu rhoncus augue, non porttitor tortor. Phasellus viverra eros ut felis aliquet tempus. Aenean eu tincidunt eros. Nam porta lorem et mauris blandit, quis auctor neque porta. In tortor justo, sagittis at metus vel, efficitur efficitur libero. Donec ac enim at ex posuere iaculis id at tellus. Etiam eu convallis felis. Duis volutpat purus ac est rutrum lacinia. Donec porttitor, sapien eu tempor pulvinar, leo enim elementum libero, vel tempus purus augue at elit. Suspendisse finibus fermentum metus sit amet pharetra. Nullam et gravida ex. Suspendisse porttitor nisl sit amet eros pulvinar, ac porta lacus molestie. Sed vel eros placerat, ultricies dolor eu, aliquam metus. Quisque varius tortor ut convallis laoreet. Phasellus tempus sem tortor, ac volutpat eros pretium at. Nulla pellentesque velit quam, sit amet hendrerit leo ultrices ac. Pellentesque a lacus commodo, blandit felis eu, varius leo. Nullam eget dui nec arcu mattis commodo nec in felis. Duis id tincidunt felis. Donec iaculis nibh a fringilla dictum. Donec scelerisque nisi nec ligula interdum placerat. Suspendisse potenti. Praesent elementum purus nibh, ac dignissim justo iaculis in. Etiam pulvinar pellentesque magna sit amet varius. Praesent sagittis metus neque, sed vulputate urna pellentesque vel. Suspendisse malesuada orci magna, sed pharetra dui venenatis in. Vivamus egestas massa eget quam condimentum, ut laoreet turpis blandit. Sed et erat velit. Maecenas eget ultricies justo. Mauris scelerisque orci vel tortor malesuada tincidunt. Ut nec est nulla. Etiam et elementum velit, sit amet fermentum est. Vestibulum hendrerit malesuada sem at ultricies. Sed eu fermentum est, nec rutrum lacus. Nunc posuere interdum semper. Mauris at risus lectus. Integer id molestie tortor, vel hendrerit metus. Duis vel nisl sapien. Phasellus sed eleifend dui.</p>
      </div>
    </div>
  )
}

export default HomePage